Update cs-guide
BrockCSC/brockcsc.github.io pull request #42
Opened 2020-07-14 15:07 UTC by firefelix

* fix courses and add note
* add minor in applied computing section
* add context credits section
* add common course types section
* add section types section
* add duration section

2020-07-14 15:14 UTC, JoelGritter requested changes

2020-07-14 15:14 UTC, JoelGritter commented on src/assets/cs-guide.md
> +C - 0 Credit (only required for co-op)
`C` _technically_ counts for 0.5 credits:
<img width="748" alt="Screen Shot 2020-07-14 at 11 13 03" src="https://user-images.githubusercontent.com/13542746/87443064-0320d780-c5c3-11ea-8da5-1dea19806777.png">

2020-07-14 15:15 UTC, JoelGritter commented on src/assets/cs-guide.md
> +C - 0 Credit (only required for co-op)
It's a little weird how it works. From what I know the weight is only there for OSAP purposes, but on Brock's side it doesn't count as a credit. (i.e. it doesn't speed up your graduation)

2020-07-15 15:01 UTC, JoelGritter approved these changes
LGTM

2020-07-16 01:06 UTC, kindeep approved these changes

2020-07-16 01:09 UTC, merged