Angular update9 to12
BrockCSC/brockcsc.github.io pull request #89
Opened 2021-07-20 02:58 UTC by CaptKillSwitch

# Changes 🛠

## What does this PR do?

## Screenshots 🖼

### Before

### After

## Any new npm dependencies?

NO

# Testing 🧪

Changes from the latest PR are deployed to https://brockcsc-pr.web.app once the checks are complete. Can use this for testing.

### Any other info neededed for testing?

NO

2021-07-20 04:18 UTC, JoelGritter commented on src/app/views/exec-applications/execapplications.component.ts
> +      url: 'https://docs.google.com/forms/d/e/1FAIpQLSfBrVc9NN552xvMBIQ36_-q8jUuuMvgNdBVn2fTM4bsgkcRqw/formResponse',
Intentionally left the URL hardcoded?

2021-07-20 04:54 UTC, kindeep commented
I would remove link from the top nav, instead maybe a link in /team saying "Apply to be an Exec"

2021-08-04 22:41 UTC, kindeep requested changes
Remove link from nav, add link to the /team page saying “Apply to be an exec”. Add another link in the signup page, just at the bottom I think. Maybe also add a link on homepage, somewhere around the “Learn about the team” button

2021-08-26 23:43 UTC, kindeep approved these changes
LGTM :shipit:

2021-08-26 23:46 UTC, merged